export default {
	CART_ADD_PRODUCT: { type: "CART_ADD_PRODUCT" },
	CART_EDIT_QUANTITY_PRODUCT: { type: "CART_EDIT_QUATITY_PRODUCT" },
	CART_DELETE_PRODUCT: { type: "CART_DELETE_PRODUCT" },
	CART_SET_SAVED_ONE: { type: "CART_SET_SAVED_ONE" },
};
